import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans, Montserrat, Raleway } from "next/font/google";
import SpaceBackground from "@/components/SpaceBackground";

const montserrat = Montserrat({
  weight: "variable",
  variable: "--montserrat",
  subsets: ["latin"],
});

const raleway = Raleway({
  weight: "variable",
  variable: "--raleway",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  weight: "variable",
  variable: "--open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${raleway.variable} ${openSans.variable}  antialiased`}
      >
        <main className="overflow-hidden relative bg-black">
          <SpaceBackground />
          {children}
        </main>
      </body>
    </html>
  );
}
